# OpenClaw Tool: forge-tool
#
# Creates new tool definitions (.nix files) for OpenClaw.
# The agent can use this tool to create new capabilities.
# Generated tools are placed in the tools directory for user review.

{
  config,
  lib,
  pkgs,
  cfg,
  ...
}:

{
  name = "forge-tool";
  description = "Create a new OpenClaw tool definition";
  permissions = "0750";

  dependencies = with pkgs; [
    coreutils
    jq
  ];

  script = ''
        #!/usr/bin/env bash
        # OpenClaw Tool: forge-tool
        # Description: Create a new OpenClaw tool definition
        #
        # Usage: forge-tool <name> <script> [--description=DESC] [--dependencies=DEPS]
        
        set -euo pipefail

        WORKSPACE="${cfg.workspace}"
        TOOLS_DIR="$WORKSPACE/tools"
        GENERATED_DIR="$TOOLS_DIR/.generated"

        # Ensure generated directory exists
        mkdir -p "$GENERATED_DIR"

        # Parse arguments
        TOOL_NAME=""
        TOOL_SCRIPT=""
        DESCRIPTION="A custom OpenClaw tool"
        DEPENDENCIES=""
        SCRIPT_FILE=""
        AUTO_APPROVE=false

        while [[ $# -gt 0 ]]; do
          case "$1" in
            --description=*)
              DESCRIPTION="''${1#*=}"
              shift
              ;;
            --dependencies=*)
              DEPENDENCIES="''${1#*=}"
              shift
              ;;
            --script-file=*)
              SCRIPT_FILE="''${1#*=}"
              shift
              ;;
            --auto-approve)
              AUTO_APPROVE=true
              shift
              ;;
            --review)
              AUTO_APPROVE=false
              shift
              ;;
            -*)
              echo "{\"error\": \"Unknown option: $1\"}" >&2
              exit 1
              ;;
            *)
              if [[ -z "$TOOL_NAME" ]]; then
                TOOL_NAME="$1"
                shift
              elif [[ -z "$TOOL_SCRIPT" && -z "$SCRIPT_FILE" ]]; then
                TOOL_SCRIPT="$1"
                shift
              else
                echo "{\"error\": \"Unexpected argument: $1\"}" >&2
                exit 1
              fi
              ;;
          esac
        done

        # Validate tool name
        if [[ -z "$TOOL_NAME" ]]; then
          echo '{"error": "Missing required argument: name"}' >&2
          exit 1
        fi

        if [[ ! "$TOOL_NAME" =~ ^[a-z][a-z0-9-]*$ ]]; then
          echo "{\"error\": \"Invalid tool name. Must be lowercase, start with a letter, and contain only letters, numbers, and dashes.\"}" >&2
          exit 1
        fi

        # Get script content
        if [[ -n "$SCRIPT_FILE" ]]; then
          if [[ ! -f "$SCRIPT_FILE" ]]; then
            echo "{\"error\": \"Script file not found: $SCRIPT_FILE\"}" >&2
            exit 1
          fi
          TOOL_SCRIPT="$(cat "$SCRIPT_FILE")"
        fi

        if [[ -z "$TOOL_SCRIPT" ]]; then
          echo '{"error": "Missing required argument: script content"}' >&2
          exit 1
        fi

        # Sanitize script (remove potential null bytes)
        TOOL_SCRIPT="$(echo "$TOOL_SCRIPT" | tr -d '\0')"

        # Check if tool already exists
        TOOL_FILE="$GENERATED_DIR/$TOOL_NAME.nix"
        if [[ -f "$TOOL_FILE" ]]; then
          echo "{\"error\": \"Tool '$TOOL_NAME' already exists. Use a different name.\"}" >&2
          exit 2
        fi

        # Format dependencies for Nix
        format_deps() {
          local deps="$1"
          if [[ -z "$deps" ]]; then
            echo "[]"
            return
          fi
          
          local result="["
          IFS=',' read -ra DEP_ARRAY <<< "$deps"
          for dep in "''${DEP_ARRAY[@]}"; do
            dep="$(echo "$dep" | xargs)" # Trim whitespace
            result="$result\"$dep\" "
          done
          result="$result]"
          echo "$result"
        }

        DEPS_NIX="$(format_deps "$DEPENDENCIES")"

        TOOL_SCRIPT="''${TOOL_SCRIPT//\'\'/\'\'\'}"
        
        TOOL_SCRIPT="''${TOOL_SCRIPT//\$\{/\'\'\$\{}"

        # Generate Nix file content
        cat > "$TOOL_FILE" << NIXFILE
    # OpenClaw Tool: $TOOL_NAME
    # Auto-generated by forge-tool
    # Description: $DESCRIPTION
    #
    # IMPORTANT: This tool was generated by the AI agent.
    # Please review before enabling in production.

    { config, lib, pkgs, cfg }:

    {
      name = "$TOOL_NAME";
      description = "$DESCRIPTION";
      permissions = "0750";
      
      dependencies = with pkgs; $DEPS_NIX;
      
      script = '''
    #!/usr/bin/env bash
    # OpenClaw Tool: $TOOL_NAME
    # Description: $DESCRIPTION
    # Status: PENDING REVIEW

    set -euo pipefail

    WORKSPACE="\''${WORKSPACE:-${cfg.workspace}}"

    $TOOL_SCRIPT
      ''';
    }
    NIXFILE

        # Set permissions
        chmod 0644 "$TOOL_FILE"

        # Create symlink for auto-approval if requested
        if [[ "$AUTO_APPROVE" == true ]]; then
          ln -sf "$TOOL_FILE" "$TOOLS_DIR/$TOOL_NAME.nix"
          STATUS="approved"
          SYMLINK="$TOOLS_DIR/$TOOL_NAME.nix"
        else
          STATUS="pending_review"
          SYMLINK=""
        fi

        # Update or create manifest safely
        if [[ -f "$GENERATED_DIR/.manifest.json" ]]; then
          jq ".tools += [{\"name\": \"$TOOL_NAME\", \"status\": \"$STATUS\", \"file\": \"$TOOL_FILE\"}]" "$GENERATED_DIR/.manifest.json" > "$GENERATED_DIR/.manifest.json.tmp"
          mv "$GENERATED_DIR/.manifest.json.tmp" "$GENERATED_DIR/.manifest.json"
        else
          cat > "$GENERATED_DIR/.manifest.json" << MANIFEST
    {
      "tools": [
        {
          "name": "$TOOL_NAME",
          "status": "$STATUS",
          "file": "$TOOL_FILE"
        }
      ]
    }
    MANIFEST
        fi

        # Output result
        cat <<EOF
    {
      "success": true,
      "tool_name": "$TOOL_NAME",
      "description": "$DESCRIPTION",
      "status": "$STATUS",
      "nix_file": "$TOOL_FILE"
    }
    EOF
  '';
}
