# OpenClaw Tool: git-agent
# Description: Agentic git tool: clone, fetch, pull, commit (local only, no push). Read-only GitHub integration.
#
# IMPORTANT: This tool was generated by the AI agent.
# Please review before enabling in production.

{
  config,
  lib,
  pkgs,
  cfg,
}:

{
  name = "git-agent";
  description = "Agentic git tool: clone, fetch, pull, commit (local only, no push). Read-only GitHub integration.";
  permissions = "0750";

  dependencies = with pkgs; [
    git
    jq
    openssh
    coreutils
  ];

  script = ''
    #!/usr/bin/env bash
    # OpenClaw Tool: git-agent
    # Description: Agentic git tool: clone, fetch, pull, commit (local only, no push). Read-only GitHub integration.
    # Status: REVIEWED

    set -euo pipefail

    OP="''${1:-}"
    [[ -z $OP ]] && echo "{\"error\": \"Usage: git-agent <clone|fetch|pull|commit|status|diff|log|branch> [args]\"}" && exit 1

    WORKSPACE="${cfg.workspace}"
    CONFIG_DIR="$WORKSPACE/.openclaw"
    CREDS_DIR="$WORKSPACE/.openclaw/credentials"

    resolve_path() {
      local p="$1"
      [[ "$p" != /* ]] && p="$WORKSPACE/$p"
      p="$(realpath -m "$p")"
      [[ "$p" =~ ^"$WORKSPACE"(/|$) ]] || { echo "{\"error\": \"Outside workspace: $p\"}" >&2; return 2; }
      [[ "$p" == "$CONFIG_DIR"* ]] && { echo "{\"error\": \".openclaw blocked\"}" >&2; return 2; }
      echo "$p"
    }

    check_push() {
      for arg in "$@"; do
        [[ "$arg" =~ ^push$|^--push$|git\.github\.com ]] && echo "{\"error\": \"Push is not allowed\"}" && exit 1
      done
    }

    get_gh_token() {
      local tok=""
      [[ -f "$CREDS_DIR/github-token" ]] && tok=$(cat "$CREDS_DIR/github-token")
      echo "$tok"
    }

    get_ssh_key() {
      local key=""
      [[ -f "$CREDS_DIR/github-ssh-key" ]] && key="$CREDS_DIR/github-ssh-key"
      echo "$key"
    }

    case $OP in
      clone)
        REPO="''${2:-}"
        [[ -z "$REPO" ]] && echo "{\"error\": \"clone needs a URL\"}" && exit 1
        check_push "$REPO"
        
        TARGET_DIR=""
        if [[ "''${3:-}" == --dir=* ]]; then
          TARGET_DIR="''${3#*=}"
          TARGET_DIR="$(resolve_path "$TARGET_DIR")" || exit 2
        else
          TARGET_DIR="$(basename "$REPO" .git)"
          TARGET_DIR="$WORKSPACE/repos/$TARGET_DIR"
        fi
        mkdir -p "$(dirname "$TARGET_DIR")"
        
        TOKEN="$(get_gh_token)"
        CLONED_SUCCESS=false
        
        if [[ "$REPO" =~ ^git@github\.com: ]]; then
          SSH_KEY="$(get_ssh_key)"
          if [[ -n "$SSH_KEY" ]]; then
            export GIT_SSH_COMMAND="ssh -i \"$SSH_KEY\" -o StrictHostKeyChecking=accept-new"
          else
            export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=accept-new"
          fi
          if git clone --recursive "$REPO" "$TARGET_DIR" 2>&1; then CLONED_SUCCESS=true; fi
        elif [[ "$REPO" =~ ^https://github\.com/ ]]; then
          if [[ -n "$TOKEN" ]]; then
            REPO="''${REPO/https:\/\/github.com\//https:\/\/x-access-token:$TOKEN@github.com\/}"
          fi
          if git clone --recursive "$REPO" "$TARGET_DIR" 2>&1; then CLONED_SUCCESS=true; fi
        else
          if git clone --recursive "$REPO" "$TARGET_DIR" 2>&1; then CLONED_SUCCESS=true; fi
        fi
        
        if [[ "$CLONED_SUCCESS" == true ]]; then
          echo "{\"success\": true, \"operation\": \"clone\", \"repo\": \"$REPO\", \"path\": \"$TARGET_DIR\", \"cloned\": true}"
        else
          echo "{\"success\": false, \"operation\": \"clone\", \"repo\": \"$REPO\", \"error\": \"Clone failed\"}"
        fi
        ;;
        
      fetch)
        WDIR="''${2:-.}"
        WDIR="$(resolve_path "$WDIR")" || exit 2
        check_push "$WDIR"
        [[ -d "$WDIR/.git" ]] || { echo "{\"error\": \"Not a git repo: $WDIR\"}" >&2; exit 1; }
        cd "$WDIR"
        RESULT=$(git fetch --all 2>&1 || true)
        echo "{\"success\": true, \"operation\": \"fetch\", \"dir\": \"$WDIR\", \"output\": $(printf "%s" "$RESULT" | jq -Rs .)}"
        ;;
        
      pull)
        WDIR="''${2:-.}"
        WDIR="$(resolve_path "$WDIR")" || exit 2
        check_push "$WDIR"
        [[ -d "$WDIR/.git" ]] || { echo "{\"error\": \"Not a git repo: $WDIR\"}" >&2; exit 1; }
        cd "$WDIR"
        REBASE=""
        [[ "''${3:-}" == --rebase ]] && REBASE="--rebase"
        RESULT=$(git pull $REBASE 2>&1 || true)
        echo "{\"success\": true, \"operation\": \"pull\", \"dir\": \"$WDIR\", \"rebase\": \"$REBASE\", \"output\": $(printf "%s" "$RESULT" | jq -Rs .)}"
        ;;
        
      commit)
        MSG="''${2:-}"
        [[ -z "$MSG" ]] && echo "{\"error\": \"commit needs a message. Usage: git-agent commit <message> [--all|-a] [dir]\"}" && exit 1
        
        WDIR="."
        STAGED=""
        for arg in "''${@:3}"; do
          if [[ "$arg" == "--all" || "$arg" == "-a" ]]; then
            STAGED="--all"
          else
            WDIR="$arg"
          fi
        done
        
        WDIR="$(resolve_path "$WDIR")" || exit 2
        check_push "$WDIR" "$MSG"
        [[ -d "$WDIR/.git" ]] || { echo "{\"error\": \"Not a git repo: $WDIR\"}" >&2; exit 1; }
        cd "$WDIR"
        
        if [[ "$STAGED" == "--all" ]]; then
          git add --all 2>/dev/null || true
        fi
        
        if HASH=$(git commit -m "$MSG" 2>&1); then
          echo "{\"success\": true, \"operation\": \"commit\", \"hash\": \"$(git log -1 --format=%H)\", \"message\": $(printf "%s" "$MSG" | jq -Rs .)}"
        else
          echo "{\"success\": false, \"error\": $(printf "%s" "$HASH" | jq -Rs .)}"
        fi
        ;;
        
      status)
        WDIR="''${2:-.}"
        SHORT=""
        if [[ "$WDIR" == "--short" || "$WDIR" == "-s" ]]; then
          SHORT="--short"
          WDIR="''${3:-.}"
        fi
        
        WDIR="$(resolve_path "$WDIR")" || exit 2
        check_push "$WDIR"
        [[ -d "$WDIR/.git" ]] || { echo "{\"error\": \"Not a git repo: $WDIR\"}" >&2; exit 1; }
        cd "$WDIR"
        
        RESULT=$(git status $SHORT 2>&1)
        echo "{\"success\": true, \"operation\": \"status\", \"dir\": \"$WDIR\", \"output\": $(printf "%s" "$RESULT" | jq -Rs .)}"
        ;;
        
      diff)
        OPT=""
        WDIR="''${2:-.}"
        if [[ "$WDIR" == "--cached" ]]; then
          OPT="--cached"
          WDIR="''${3:-.}"
        fi
        
        WDIR="$(resolve_path "$WDIR")" || exit 2
        check_push "$WDIR"
        [[ -d "$WDIR/.git" ]] || { echo "{\"error\": \"Not a git repo: $WDIR\"}" >&2; exit 1; }
        cd "$WDIR"
        
        RESULT=$(git diff $OPT 2>&1)
        echo "{\"success\": true, \"operation\": \"diff\", \"dir\": \"$WDIR\", \"cached\": $([[ "$OPT" == "--cached" ]] && echo true || echo false), \"output\": $(printf "%s" "$RESULT" | jq -Rs .)}"
        ;;
        
      log)
        NUM=10
        ONE=""
        WDIR="."
        for arg in "''${@:2}"; do
          if [[ "$arg" =~ ^-n[0-9]+$ ]]; then NUM="''${arg#-n}"
          elif [[ "$arg" == "--oneline" ]]; then ONE="--oneline"
          else WDIR="$arg"
          fi
        done
        
        WDIR="$(resolve_path "$WDIR")" || exit 2
        check_push "$WDIR"
        [[ -d "$WDIR/.git" ]] || { echo "{\"error\": \"Not a git repo: $WDIR\"}" >&2; exit 1; }
        cd "$WDIR"
        
        ENTRIES_JSON=$(git log $ONE -n $NUM --format="%H%x00%an%x00%ai%x00%s" 2>/dev/null | jq -Rs -c '[split("\n")[] | select(length > 0) | split("\u0000") | {hash: .[0], author: .[1], date: .[2], message: .[3]}]')
        echo "{\"success\": true, \"operation\": \"log\", \"dir\": \"$WDIR\", \"count\": $NUM, \"entries\": $ENTRIES_JSON}"
        ;;
        
      branch)
        WDIR="."
        ALLB=""
        VERBOSE=""
        for arg in "''${@:2}"; do
          if [[ "$arg" == "-a" ]]; then ALLB="-a"
          elif [[ "$arg" == "-v" ]]; then VERBOSE="-v"
          else WDIR="$arg"
          fi
        done
        
        WDIR="$(resolve_path "$WDIR")" || exit 2
        check_push "$WDIR"
        [[ -d "$WDIR/.git" ]] || { echo "{\"error\": \"Not a git repo: $WDIR\"}" >&2; exit 1; }
        cd "$WDIR"
        
        RESULT=$(git branch $ALLB $VERBOSE 2>&1)
        echo "{\"success\": true, \"operation\": \"branch\", \"dir\": \"$WDIR\", \"branches\": $(printf "%s" "$RESULT" | jq -Rs .)}"
        ;;
        
      *)
        echo "{\"error\": \"Unknown operation: $OP. Use clone, fetch, pull, commit, status, diff, log, or branch\"}" && exit 1 
        ;;
    esac
  '';
}
