# OpenClaw Tool: patch-file
# Description: Apply unified diff to a file. Use when multi-hunk edits are needed.
#
# IMPORTANT: This tool was generated by the AI agent.
# Please review before enabling in production.

{
  config,
  lib,
  pkgs,
  cfg,
}:

{
  name = "patch-file";
  description = "Apply unified diff to a file. Use when multi-hunk edits are needed.";
  permissions = "0750";

  dependencies = with pkgs; [
    patch
    coreutils
    gnugrep
  ];

  script = ''
    #!/usr/bin/env bash
    # OpenClaw Tool: patch-file
    # Description: Apply unified diff to a file. Use when multi-hunk edits are needed.
    # Status: REVIEWED

    set -euo pipefail

    FILE="''${1:-}"
    [[ -z $FILE ]] && echo "{\"error\": \"Usage: patch-file <file>\"}" && exit 1

    WORKSPACE="${cfg.workspace}"
    CONFIG_DIR="$WORKSPACE/.openclaw"

    [[ $FILE != /* ]] && FILE="$WORKSPACE/$FILE"
    FILE=$(realpath -m "$FILE")

    [[ $FILE =~ ^$WORKSPACE(/|$) ]] || { echo "{\"error\": \"Outside workspace\"}"; exit 2; }
    [[ $FILE == $CONFIG_DIR* ]] && { echo "{\"error\": \".openclaw blocked\"}"; exit 2; }

    TEMP=$(mktemp)
    trap 'rm -f "$TEMP"' EXIT
    cat > "$TEMP"

    # Run patch in batch mode to prevent hanging on bad diffs.
    # Capture output to properly count hunks and avoid silent pipefail exits.
    if ! OUTPUT=$(patch --batch --no-backup-if-mismatch "$FILE" < "$TEMP" 2>&1); then
      echo "{\"error\": \"Patch failed. Check stderr for details.\"}" >&2
      echo "$OUTPUT" >&2
      exit 1
    fi

    # Count how many times patch reported applying a hunk
    HUNKS=$(echo "$OUTPUT" | grep -c "patching" || echo 0)

    echo "{\"success\": true, \"operation\": \"patch\", \"file\": \"$FILE\", \"hunks_applied\": $HUNKS}"
  '';
}
