# OpenClaw Tool: sed-inplace
# Description: In-place line editing via GNU sed. Delete/replace/insert without rewriting entire files.
#
# IMPORTANT: This tool was generated by the AI agent.
# Please review before enabling in production.

{
  pkgs,
  cfg,
  ...
}:

{
  name = "sed-inplace";
  description = "In-place line editing via GNU sed. Delete/replace/insert without rewriting entire files.";
  permissions = "0750";

  dependencies = with pkgs; [
    gnused
    coreutils
  ];

  script = ''
    #!/usr/bin/env bash
    # OpenClaw Tool: sed-inplace
    # Description: In-place line editing via GNU sed. Delete/replace/insert without rewriting entire files.
    # Status: REVIEWED

    set -euo pipefail

    FILE="''${1:-}"
    OP="''${2:-}"

    [[ -z $OP || -z $FILE ]] && echo "{\"error\": \"Usage: sed-inplace <file> <--delete|--replace|--insert|--substitute> [args]\"}" && exit 1

    WORKSPACE="${cfg.workspace}"
    CONFIG_DIR="$WORKSPACE/.openclaw"

    [[ $FILE != /* ]] && FILE="$WORKSPACE/$FILE"
    FILE=$(realpath -m "$FILE")

    [[ $FILE =~ ^$WORKSPACE(/|$) ]] || { echo "{\"error\": \"Outside workspace\"}"; exit 2; }
    [[ $FILE == $CONFIG_DIR* ]] && { echo "{\"error\": \".openclaw blocked\"}"; exit 2; }

    case $OP in
      --delete)
        RANGE="''${3:-}"
        [[ -z $RANGE ]] && echo "{\"error\": \"Usage: sed-inplace <file> --delete <range>\", \"example\": \"sed-inplace file.txt --delete 5,10\"}" && exit 1
        sed -i "''${RANGE}d" "$FILE"
        LINES=$(wc -l < "$FILE")
        echo "{\"success\": true, \"operation\": \"delete\", \"range\": \"$RANGE\", \"file\": \"$FILE\", \"remaining_lines\": $LINES}"
        ;;
      --replace)
        PAT="''${3:-}"
        REP="''${4:-}"
        [[ -z $PAT || -z $REP ]] && echo "{\"error\": \"Usage: sed-inplace <file> --replace <pattern> <replacement>\"}" && exit 1
        sed -i "s|$PAT|$REP|g" "$FILE"
        echo "{\"success\": true, \"operation\": \"replace\", \"pattern\": \"$PAT\", \"replacement\": \"$REP\", \"file\": \"$FILE\"}"
        ;;
      --insert)
        LINE="''${3:-}"
        CONTENT="''${4:-}"
        [[ -z $LINE || -z $CONTENT ]] && echo "{\"error\": \"Usage: sed-inplace <file> --insert <linenum> <text>\"}" && exit 1
        sed -i "''${LINE}a\\$CONTENT" "$FILE"
        echo "{\"success\": true, \"operation\": \"insert\", \"after_line\": $LINE, \"file\": \"$FILE\"}"
        ;;
      --substitute)
        EXPR="''${3:-}"
        [[ -z $EXPR ]] && echo "{\"error\": \"Usage: sed-inplace <file> --substitute <sed-expr>\"}" && exit 1
        sed -i "$EXPR" "$FILE"
        echo "{\"success\": true, \"operation\": \"substitute\", \"expr\": \"$EXPR\", \"file\": \"$FILE\"}"
        ;;
      *) 
        echo "{\"error\": \"Unknown operation: $OP. Use --delete, --replace, --insert, or --substitute\"}"; exit 1 
        ;;
    esac
  '';
}
