{
  config,
  inputs,
  ...
}:
{
  imports = [
    inputs.forge.homeManagerModules.default
  ];

  forge = {
    enable = true;
    syncBase = "${config.home.homeDirectory}/sync";
    githubUser = "AMarek05";
    languages = [
      "rust"
      "python"
      "c"
      "cpp"
      "java"
      "nix"
      "r"
    ];
    includes = [
      "git"
      "overseer"
    ];
  };

  # Load zsh completions generated by the forge package's postInstall
  programs.zsh.completions = [
    "${config.forge.package}/share/zsh/site-functions"
  ];
}
