keys:
  - &my_machine age1584m9pltvjddn2hk9kd6w073u3k85s2crrw3zgctahd8csew4a5sdx2730
  - &my_machine_personal age16humsqez84yttsmm9kgw7yejv6a5q44hhgx6ac4praymk88rkdeqeqhfqg

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *my_machine
          - *my_machine_personal
