#!/usr/bin/env bash
set -e

REPO="/home/adam/sys"
ETC="/home/adam/sys/etc"
FLAKE="/home/adam/sys/flake.nix"

cd "$REPO"

nvim "${ETC}/configuration.nix"

git add "$ETC" "$FLAKE"
echo "Proceeding to rebuild:"

nh os switch

git commit -m "$(date +'%H:%M - %d %B %Y')"

