#!/usr/bin/env bash
set -e

REPO="/home/adam/sys"

MODULES="/home/adam/sys/modules"

nvim "$MODULES/defaults.nix"

cd "$REPO"

nh home switch

git add "$MODULES"
git commit -m "$(date +'%H:%M - %d %B %Y')"
