#!/usr/bin/env bash
set -e

REPO="/home/adam/sys"

MODULES="${REPO}/modules"
STORE="${REPO}/store"
HOSTS="${REPO}/hosts"
FLAKE="${REPO}/flake.nix"

cd "$REPO"

git add "$HOSTS" "$MODULES" "$STORE" "$FLAKE"

nh home switch

git commit -m "$(date +'%H:%M - %d %B %Y')"
