#!/usr/bin/env bash
set -e

REPO="/home/adam/sys"

MODULES="${REPO}/modules"
STORE="${REPO}/store"
HOSTS="${REPO}/hosts"
FLAKE="${REPO}/flake.nix"

nvim "${MODULES}/defaults.nix"

cd "$REPO"

nh home switch

git add "$MODULES" "$STORE" "$HOSTS" "$FLAKE"
git commit -m "$(date +'%H:%M - %d %B %Y')"
