#!/usr/bin/env bash
set -e

REPO="/home/adam/sys/"

MODULES="/home/adam/sys/modules/"
HOSTS="/home/adam/sys/hosts/"
STORE="/home/adam/sys/store/"

cd "$REPO"

git add "$HOSTS" "$MODULES" "$STORE"

nh home switch

git commit -m "$(date +'%H:%M - %d %B %Y')"
