#!/usr/bin/env bash
set -e

REPO="/home/adam/sys"

MODULES="/home/adam/sys/modules"
STORE="/home/adam/sys/store"
HOSTS="/home/adam/sys/hosts/"
FLAKE=/home/adam/sys/flake.nix

nvim "$MODULES/defaults.nix"

cd "$REPO"

nh home switch

git add "$MODULES" "$STORE" "$HOSTS" "$FLAKE"
git commit -m "$(date +'%H:%M - %d %B %Y')"
