#!/usr/bin/env bash
set -e

REPO="/home/adam/sys/"

CONF="/home/adam/sys/home.nix"
MODULES="/home/adam/sys/modules/"

nvim "$CONF"

cd "$REPO"

nh home switch

git add "$CONF" "$MODULES"
git commit -m "$(date +'%H:%M - %d %B %Y')"
